---
title: "R Notebook"
output: pdf_notebook
author: "James Osmin Gramajo Carcamo"
---

Assigment 5


```{r}
library(dplyr)

#Load the data
questions_file <- read.csv("questions.csv")
answers_file <- read.csv("answers.csv")
tags_file <- read.csv("tags.csv")
question_tags_file <- read.csv("question_tags.csv")
```

1. Left-joining questions and tags
```{r}

#1.1 RelationShip between 'questions' and 'question_tags' using id and question_id
questions_tags_relationship <- left_join(questions_file, question_tags_file, by = c("id" = "question_id"))

#1.2 Add a relationship for tags table
questions_tags_relationship <- left_join(questions_tags_relationship, tags_file, by = c("tag_id" = "id"))

#1.3 Use (replace_na) for change NA values in the column tag_name to "only-r"
questions_tags_relationship$tag_name <- replace_na(questions_tags_relationship$tag_name, "only-r")

#1.4 Save the variable in questions_with_tags
questions_with_tags <- questions_tags_relationship
questions_with_tags

```

2. Comparing scores across tags
```{r}
#2.1 to 2.3
comparing_scores <- questions_with_tags %>%
  group_by(tag_name)  %>% #Group by tag
  summarize(mean_score = mean(score)) %>% #2.2 Return the avg score for each question
  arrange(desc(mean_score)) #order mean_score in desc

print(comparing_scores)

```

3 Finding gaps between questions and answers
```{r}
#Use inner join

#3.1 Use inner_join and assign suffix
questions_and_answers <- inner_join(questions_file, answers_file, by = c("id" = "question_id"), suffix = c("_question", "_answer"))

#3.2 Add new column gap to show difference between dates
questions_and_answers <- questions_and_answers %>%
  mutate(gap = as.Date(creation_date_answer) - as.Date(creation_date_question))
print(questions_and_answers)
```
4 Joining question and answer counts
```{r}
#4.1 Count and sort the question_id column in the answers table, then store the result in the answer_counts variable.
answer_counts <- answers_file %>%
  count(question_id) %>%
  arrange(desc(n))
answer_counts

#4.2 Relate the questions table to answer_counts (use left_join).
question_answer_counts <- left_join(questions_file, answer_counts, by = c("id" = "question_id")) %>%
  mutate(n = replace_na(n, 0)) #4.3 Replace the NA values in column n with zeros.

#4.4 Finally, store the result in the question variable answer_counts.
question_answer_counts
```
5 Joining questions, answers, and tags
```{r}
#5.1. Combine question_tags with question_answer_counts using an inner_join.
questions_tags <- inner_join(question_tags_file, question_answer_counts, by = c("question_id" = "id"))

#5.2. Now, use another inner_join to add the tags table.
questions_tags_answers <- inner_join(questions_tags, tags_file, by = c("tag_id" = "id"))
questions_tags_answers

```

